### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by strongstancer** [Krappa322/arcdps_unofficial_extras_releases#1]
Installed it as written. Getting a Error:
1.078: warning: failed to load "arcdps_unofficial_extras.dll", extension provided reason: Failed to inject hook 5

just updated to the most recent arc version

**Comment by midadami** [comment]
Same.

**Comment by Krappa322** [comment]
Thanks for reporting :) Should be fixed now

https://github.com/Krappa322/arcdps_unofficial_extras_releases/releases/tag/v1.1.rc1

**Comment by TrYkeRm4N** [comment]
Thanks @Krappa322 for your fast reply.

At least for me, still crashing on dx11.

This is what I try:

Place at /bin64/   -> Not crashing when open Killproof window on arc. But extra features are not loaded.
Place at /  -> Crashing when open Killproof window on arc.
Place at /  & Place at /bin64/   -> Not crashing when open Killproof window on arc. But extra features are not loaded.

Thanks again!

**Comment by Krappa322** [comment]
@TrYkeRm4N Are you using the latest version? There was one released just yesterday that fixed dx11 init

https://github.com/Krappa322/arcdps_unofficial_extras_releases/releases/tag/v1.1.rc2

**Comment by TrYkeRm4N** [comment]
nvm, I place it again on both folders and now it doesnt crash. 

Dunno but if it works, I wont touch it more.

Thanks again
